models = {
    "m": {
        "HGNetv2": {
            "pretrained": False,
            "local_model_dir": "weight/hgnetv2/",
            "name": "B2",
            "return_idx": [1, 2, 3],
            "freeze_at": -1,
            "freeze_norm": False,
            "use_lab": True,
        },
        "HybridEncoder": {
            "in_channels": [384, 768, 1536],
            "feat_strides": [8, 16, 32],
            "hidden_dim": 256,
            "use_encoder_idx": [2],
            "num_encoder_layers": 1,
            "nhead": 8,
            "dim_feedforward": 1024,
            "dropout": 0.0,
            "enc_act": "gelu",
            "expansion": 1.0,
            "depth_mult": 0.67,
            "act": "silu",
        },
        "DFINETransformer": {
            "feat_channels": [256, 256, 256],
            "feat_strides": [8, 16, 32],
            "hidden_dim": 256,
            "num_levels": 3,
            "num_layers": 4,
            "eval_idx": -1,
            "num_queries": 300,
            "num_denoising": 100,
            "label_noise_ratio": 0.5,
            "box_noise_scale": 1.0,
            "reg_max": 32,
            "reg_scale": 4,
            "layer_scale": 1,
            "num_points": [3, 6, 3],
            "cross_attn_method": "default",
            "query_select_method": "default",
        },
        "DFINECriterion": {
            "weight_dict": {
                "loss_vfl": 1,
                "loss_bbox": 5,
                "loss_giou": 2,
                "loss_fgl": 0.15,
                "loss_ddf": 1.5,
            },
            "losses": ["vfl", "boxes", "local"],
            "alpha": 0.75,
            "gamma": 2.0,
            "reg_max": 32,
        },
        "matcher": {
            "weight_dict": {"cost_class": 2, "cost_bbox": 5, "cost_giou": 2},
            "alpha": 0.25,
            "gamma": 2.0,
            "use_focal_loss": True,
        },
    },
}


# {
#     "task": "detection",
#     "_model": None,
#     "_postprocessor": None,
#     "_criterion": None,
#     "_optimizer": None,
#     "_lr_scheduler": None,
#     "_lr_warmup_scheduler": None,
#     "_train_dataloader": None,
#     "_val_dataloader": None,
#     "_ema": None,
#     "_scaler": None,
#     "_train_dataset": None,
#     "_val_dataset": None,
#     "_collate_fn": None,
#     "_evaluator": None,
#     "_writer": None,
#     "num_workers": 0,
#     "batch_size": None,
#     "_train_batch_size": None,
#     "_val_batch_size": None,
#     "_train_shuffle": None,
#     "_val_shuffle": None,
#     "resume": None,
#     "tuning": "dfine_m_coco.pth",
#     "epoches": 70,
#     "last_epoch": -1,
#     "use_amp": True,
#     "use_ema": True,
#     "ema_decay": 0.9999,
#     "ema_warmups": 2000,
#     "sync_bn": True,
#     "clip_max_norm": 0.1,
#     "find_unused_parameters": False,
#     "seed": 0,
#     "print_freq": 100,
#     "checkpoint_freq": 12,
#     "output_dir": "./output/dfine_hgnetv2_m_obj2custom",
#     "summary_dir": None,
#     "device": "",
#     "yaml_cfg": {
#         "task": "detection",
#         "evaluator": {"type": "CocoEvaluator", "iou_types": ["bbox"]},
#         "num_classes": 2,
#         "remap_mscoco_category": False,
#         "train_dataloader": {
#             "type": "DataLoader",
#             "dataset": {
#                 "type": "CocoDetection",
#                 "img_folder": "/home/argo/Desktop/Projects/Veryfi/hw/dataset/train/images",
#                 "ann_file": "/home/argo/Desktop/Projects/Veryfi/hw/dataset/train_annotations.json",
#                 "return_masks": False,
#                 "transforms": {
#                     "type": "Compose",
#                     "ops": [
#                         {"type": "RandomPhotometricDistort", "p": 0.5},
#                         {"type": "RandomZoomOut", "fill": 0},
#                         {"type": "RandomIoUCrop", "p": 0.8},
#                         {"type": "SanitizeBoundingBoxes", "min_size": 1},
#                         {"type": "RandomHorizontalFlip"},
#                         {"type": "Resize", "size": [960, 960]},
#                         {"type": "SanitizeBoundingBoxes", "min_size": 1},
#                         {"type": "ConvertPILImage", "dtype": "float32", "scale": True},
#                         {"type": "ConvertBoxes", "fmt": "cxcywh", "normalize": True},
#                     ],
#                     "policy": {
#                         "name": "stop_epoch",
#                         "epoch": 62,
#                         "ops": ["RandomPhotometricDistort", "RandomZoomOut", "RandomIoUCrop"],
#                     },
#                 },
#             },
#             "shuffle": True,
#             "num_workers": 4,
#             "drop_last": True,
#             "collate_fn": {
#                 "type": "BatchImageCollateFunction",
#                 "base_size": 960,
#                 "base_size_repeat": 6,
#                 "stop_epoch": 62,
#                 "ema_restart_decay": 0.9999,
#             },
#             "total_batch_size": 5,
#         },
#         "val_dataloader": {
#             "type": "DataLoader",
#             "dataset": {
#                 "type": "CocoDetection",
#                 "img_folder": "/home/argo/Desktop/Projects/Veryfi/hw/dataset/val/images",
#                 "ann_file": "/home/argo/Desktop/Projects/Veryfi/hw/dataset/val_annotations.json",
#                 "return_masks": False,
#                 "transforms": {
#                     "type": "Compose",
#                     "ops": [
#                         {"type": "Resize", "size": [960, 960]},
#                         {"type": "ConvertPILImage", "dtype": "float32", "scale": True},
#                     ],
#                 },
#             },
#             "shuffle": False,
#             "num_workers": 4,
#             "drop_last": False,
#             "collate_fn": {"type": "BatchImageCollateFunction"},
#             "total_batch_size": 5,
#         },
#         "print_freq": 100,
#         "output_dir": "./output/dfine_hgnetv2_m_obj2custom",
#         "checkpoint_freq": 12,
#         "sync_bn": True,
#         "find_unused_parameters": False,
#         "use_amp": True,
#         "scaler": {"type": "GradScaler", "enabled": True},
#         "use_ema": True,
#         "ema": {"type": "ModelEMA", "decay": 0.9999, "warmups": 0, "start": 0},
#         "epoches": 70,
#         "clip_max_norm": 0.1,
#         "optimizer": {
#             "type": "AdamW",
#             "params": [
#                 {"params": "^(?=.*backbone)(?!.*norm|bn).*$", "lr": 2.5e-05},
#                 {"params": "^(?=.*backbone)(?=.*norm|bn).*$", "lr": 2.5e-05, "weight_decay": 0.0},
#                 {
#                     "params": "^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$",
#                     "weight_decay": 0.0,
#                 },
#             ],
#             "lr": 0.00025,
#             "betas": [0.9, 0.999],
#             "weight_decay": 0.000125,
#         },
#         "lr_scheduler": {"type": "MultiStepLR", "milestones": [500], "gamma": 0.1},
#         "lr_warmup_scheduler": {"type": "LinearWarmup", "warmup_duration": 0},
#         "model": "DFINE",
#         "criterion": "DFINECriterion",
#         "postprocessor": "DFINEPostProcessor",
#         "use_focal_loss": True,
#         "eval_spatial_size": [960, 960],
#         "DFINE": {"backbone": "HGNetv2", "encoder": "HybridEncoder", "decoder": "DFINETransformer"},
#         "HGNetv2": {
#             "pretrained": False,
#             "local_model_dir": "weight/hgnetv2/",
#             "name": "B2",
#             "return_idx": [1, 2, 3],
#             "freeze_at": -1,
#             "freeze_norm": False,
#             "use_lab": True,
#         },
#         "HybridEncoder": {
#             "in_channels": [384, 768, 1536],
#             "feat_strides": [8, 16, 32],
#             "hidden_dim": 256,
#             "use_encoder_idx": [2],
#             "num_encoder_layers": 1,
#             "nhead": 8,
#             "dim_feedforward": 1024,
#             "dropout": 0.0,
#             "enc_act": "gelu",
#             "expansion": 1.0,
#             "depth_mult": 0.67,
#             "act": "silu",
#         },
#         "DFINETransformer": {
#             "feat_channels": [256, 256, 256],
#             "feat_strides": [8, 16, 32],
#             "hidden_dim": 256,
#             "num_levels": 3,
#             "num_layers": 4,
#             "eval_idx": -1,
#             "num_queries": 300,
#             "num_denoising": 100,
#             "label_noise_ratio": 0.5,
#             "box_noise_scale": 1.0,
#             "reg_max": 32,
#             "reg_scale": 4,
#             "layer_scale": 1,
#             "num_points": [3, 6, 3],
#             "cross_attn_method": "default",
#             "query_select_method": "default",
#         },
#         "DFINEPostProcessor": {"num_top_queries": 300},
#         "DFINECriterion": {
#             "weight_dict": {
#                 "loss_vfl": 1,
#                 "loss_bbox": 5,
#                 "loss_giou": 2,
#                 "loss_fgl": 0.15,
#                 "loss_ddf": 1.5,
#             },
#             "losses": ["vfl", "boxes", "local"],
#             "alpha": 0.75,
#             "gamma": 2.0,
#             "reg_max": 32,
#             "matcher": {
#                 "type": "HungarianMatcher",
#                 "weight_dict": {"cost_class": 2, "cost_bbox": 5, "cost_giou": 2},
#                 "alpha": 0.25,
#                 "gamma": 2.0,
#             },
#         },
#         "__include__": [
#             "../../../dataset/custom_detection.yml",
#             "../../../runtime.yml",
#             "../../include/dataloader.yml",
#             "../../include/optimizer.yml",
#             "../../include/dfine_hgnetv2.yml",
#         ],
#         "config": "configs/dfine/custom/objects365/dfine_hgnetv2_m_obj2custom.yml",
#         "tuning": "dfine_m_coco.pth",
#         "seed": 0,
#         "test_only": False,
#         "print_method": "builtin",
#         "print_rank": 0,
#     },
# }
